[workspace]
members = ["crates/cli", "crates/interpreter", "crates/common"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
rust-version = "1.78"

[workspace.dependencies]
eql-interpreter = { path = "crates/interpreter" }
eql-common = { path = "crates/common" }
eql-cli = { path = "crates/cli" }
