[package]
name = "eql_common"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
tabled = "0.15.0"
alloy = { version = "0.1.2", features = ["full"] }
